[node]
# the private spend key of the signer
signer-key = "56a7904a2dfd71c397bb48584033d8cb6ddcde9b46b7d91f07d2ede061723a0b"
# limit the peers that can establish a connection and exchange snapshots
consensus-only = false
# the period in seconds to check some mint and election kernel opportunities
kernel-operation-period = 700
# the maximum cache size in MB
memory-cache-size = 16384
# how many seconds to keep unconfirmed transactions in the cache storage
# this also limits the confirmed snapshots finalization cache to peer
cache-ttl = 7200
# how many cache peer snapshots to keep in the memory queue
ring-cache-size = 1048576
# how many final peer snapshots to keep in the memory queue
ring-final-size = 16777216

[network]
# the public endpoint to receive peer packets, may be a proxy or load balancer
# must be a public reachable domain or IP, and the port allowed by firewall
listener = "mixin-node.example.com:7239"

[rpc]
# whether respond the runtime of each RPC call
runtime = false
